In [ ]:
import torch

In [ ]:
x=torch.tensor([2.0,3.0,4.0])
y=torch.tensor([[2,3],
                [4,5]])

In [ ]:
print(x)
print(y)

tensor([2., 3., 4.])
tensor([[2, 3],
        [4, 5]])


In [ ]:
x.shape


torch.Size([3])

In [ ]:
y.shape

torch.Size([2, 2])

In [ ]:

z=torch.tensor([1,2,3,4,5,6])
z_2d=z.view(2,3)

In [ ]:
print(z_2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
a=torch.tensor([2,3])
b=torch.tensor([5,7])


In [ ]:
print(a+b)

tensor([ 7, 10])


In [ ]:
print(a*b)

tensor([10, 21])


In [ ]:
print(torch.relu(torch.tensor([-1.0,5.0])))

tensor([0., 5.])


In [ ]:
X=torch.tensor([[2,4,5],
               [4,7,8]])
Y=torch.tensor([[3,4],
               [3,9],
               [6,7]])
Z=X@Y
Z_mat=torch.matmul(X,Y)
print("X and Y Matrix Multiplication:",Z)
print("X and Y Matrix Multiplication using the Pytorch:",Z_mat)

X and Y Matrix Multiplication: tensor([[ 48,  79],
        [ 81, 135]])
X and Y Matrix Multiplication using the Pytorch: tensor([[ 48,  79],
        [ 81, 135]])


Autograd, Computational Graphs, and Backpropagation.


In [ ]:
import torch

In [ ]:
w=torch.tensor([3.0],requires_grad=True)
x=torch.tensor([4.0])
y=w*x
y.backward()
print(w.grad)

tensor([4.])


In [ ]:
import torch
import torch.nn as nn


# nn.Module and nn.Linear

In [ ]:
class SimpleNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    self.Layer1=nn.Linear(in_features=2,out_features=1)
  def forward(self,x):
    return self.Layer1(x)
model=SimpleNetwork()
dummy_input=torch.tensor([2.0,3.0])
prediction=model(dummy_input)

print("Model Prediction",prediction)

Model Prediction tensor([1.2925], grad_fn=<ViewBackward0>)


#  The Full Training Loop Components


In [ ]:
import torch.optim as optim

criterian=nn.MSELoss()
optimizer=optim.SGD(model.parameters(),lr=0.01)

prediction=model(dummy_input)
target=torch.tensor([3.0])

Loss=criterian(prediction,target)
print("Loss:",Loss.item())

optimizer.zero_grad()
Loss.backward()
optimizer.step()

Loss: 2.9155831336975098


In [ ]:
import torch
import torch.nn as nn

class MultiLayerPerceptron(nn.Module):
  def __init__(self,input_size,hidden_size,output_size):
    super().__init__()
    self.hidden_layer_layer=nn.Linear(input_size,hidden_size)
    self.output_layer=nn.Linear(hidden_size,output_size)
    self.relu=nn.ReLU()
  def forward(self,x):
    x=self.hidden_layer(x)
    x=self.relu(x)
    out=self.output_layer(x)
    return out
model=MultiLayerPerceptron(input_size=4,hidden_size=10,output_size=1)
print(model)




MultiLayerPerceptron(
  (hidden_layer_layer): Linear(in_features=4, out_features=10, bias=True)
  (output_layer): Linear(in_features=10, out_features=1, bias=True)
  (relu): ReLU()
)


In [ ]:
import torch
dummy_image=torch.randn(1,3,32,32)
print(dummy_image)

tensor([[[[ 0.4043,  1.2815, -0.1395,  ..., -0.4244,  0.2833, -0.7005],
          [-0.0342,  1.7716, -0.1571,  ..., -0.6413, -2.2477,  0.9817],
          [ 0.8197, -1.1717,  1.3920,  ..., -0.9838, -0.5415,  0.8080],
          ...,
          [-1.1375, -0.9731,  1.1256,  ..., -0.2139, -0.1316, -0.8391],
          [-0.4927, -0.1980, -0.3013,  ...,  0.7281,  0.7344, -0.0474],
          [-0.7528, -0.0399,  1.4997,  ...,  0.5131, -1.3735,  0.9959]],

         [[-0.0359,  0.8951,  0.0645,  ...,  1.2161, -0.2768,  0.5187],
          [-1.3058, -0.9406, -1.0095,  ...,  1.5004,  0.9987, -1.7246],
          [ 0.0241, -2.7776,  0.7258,  ..., -0.6954, -1.3608, -0.2138],
          ...,
          [ 1.6161,  0.0465, -0.6903,  ...,  1.2286,  0.6575,  0.3324],
          [-0.0842,  0.3667,  0.6776,  ...,  0.5150,  1.1700, -0.2785],
          [-1.4686,  0.2436,  0.0946,  ..., -0.3817, -0.0675, -0.7267]],

         [[ 0.2193,  0.5834,  1.7866,  ...,  0.9527,  0.7497,  0.7255],
          [ 0.4004, -1.0937, -

In [ ]:
import torch.nn as nn
convo_layer=nn.Conv2d(in_channels=3,out_channels=16,kernel_size=3)
feature_maps=convo_layer(dummy_image)
print("Feature maps shape: ",feature_maps.shape)

Feature maps shape:  torch.Size([1, 16, 30, 30])


In [ ]:
pool_layer=nn.MaxPool2d(kernel_size=2, stride=2)
pooled_maps=pool_layer(feature_maps)
print("pooled shape",pooled_maps.shape)

pooled shape torch.Size([1, 16, 15, 15])


In [ ]:
import torch
dummy_sequence=torch.randn(1,5,10)
print("dummy sequence shape is :",dummy_sequence.shape)

dummy sequence shape is : torch.Size([1, 5, 10])


In [ ]:
import torch.nn as nn
rnn=nn.RNN(input_size=10,hidden_size=20,batch_first=True)
output, final_hidden_state=rnn(dummy_sequence)
print("output Shape :",output.shape)
print("final hidden shape:",final_hidden_state.shape)

output Shape : torch.Size([1, 5, 20])
final hidden shape: torch.Size([1, 1, 20])


In [ ]:
lstm=nn.LSTM(input_size=10,hidden_size=20,batch_first=True)
output,(final_hidden_state,final_cell_state)=lstm(dummy_sequence)
print("output Shape :",output.shape)
print("final hidden shape:",final_hidden_state.shape)
print("final cell shape:",final_cell_state.shape)

output Shape : torch.Size([1, 5, 20])
final hidden shape: torch.Size([1, 1, 20])
final cell shape: torch.Size([1, 1, 20])


In [ ]:
gru=nn.GRU(input_size=10,hidden_size=20,batch_first=True)
output,final_hidden_size=gru(dummy_sequence)
print("output Shape :",output.shape)
print("final hidden shape:",final_hidden_state.shape)

output Shape : torch.Size([1, 5, 20])
final hidden shape: torch.Size([1, 1, 20])


In [ ]:
import torch
import torch.nn as nn
english_sequence=torch.rand(1,5,10)
french_sequence=torch.rand(1,5,10)

encoder=nn.LSTM(input_size=10,hidden_size=20,batch_first=True)
decoder=nn.LSTM(input_size=10,hidden_size=20,batch_first=True)

_,(context_vector,cell_state)=encoder(english_sequence)
output,_=decoder(french_sequence,(context_vector,cell_state))

In [ ]:
import torch
import torch.nn.functional as F

sequence=torch.randn(1,5,8)
Q=torch.rand(1,5,8)
K=torch.rand(1,5,8)
V=torch.rand(1,5,8)

attention_scores=Q@K.transpose(1,2)
print("Attention Shapes:",attention_scores.shape)
attention_weights=F.softmax(attention_scores,dim=-1)

final_output=attention_weights@V

print("final Output shape:",final_output.shape)


Attention Shapes: torch.Size([1, 5, 5])
final Output shape: torch.Size([1, 5, 8])


In [ ]:
import torch
import torch.nn.functional as F
import torch.nn as nn
import math

print("=== 1. SCALED DOT-PRODUCT ATTENTION (The Math) ===")

# Let's say our sentence is 5 words long, and each word has an embedding size of 8
sequence = torch.randn(1, 5, 8)

# Create Query, Key, and Value tensors of the same size
Q = torch.randn(1, 5, 8)
K = torch.randn(1, 5, 8)
V = torch.randn(1, 5, 8)

# The size of our embedding (d_k)
d_k = 8

# Multiply Q and K^T, then scale down by the square root of d_k
attention_scores = (Q @ K.transpose(1, 2)) / math.sqrt(d_k)

# Apply Softmax to get percentages
attention_weights = F.softmax(attention_scores, dim=-1)

# Multiply by V to get the final output
final_output = attention_weights @ V

print("Manual Attention Output Shape:", final_output.shape)
# Expected Output: torch.Size([1, 5, 8])

print("\n-------------------------------------------------\n")

print("=== 2. MULTI-HEAD ATTENTION (The PyTorch Way) ===")

# In reality, we don't write that math manually. PyTorch does it for us!
# embed_dim = 8 (The size of our word vectors)
# num_heads = 2 (We want 2 parallel attention 'brains')
# batch_first = True (Because our tensor starts with Batch Size)
multihead_attn = nn.MultiheadAttention(embed_dim=8, num_heads=2, batch_first=True)

# For Self-Attention, we pass the EXACT SAME sentence in as the Query, Key, and Value!
# PyTorch will automatically split it up, do the scaled math, and merge the heads.
attn_output, attn_weights = multihead_attn(query=sequence, key=sequence, value=sequence)

print("Multi-Head Attention Output Shape:", attn_output.shape)
# Expected Output: torch.Size([1, 5, 8])

=== 1. SCALED DOT-PRODUCT ATTENTION (The Math) ===
Manual Attention Output Shape: torch.Size([1, 5, 8])

-------------------------------------------------

=== 2. MULTI-HEAD ATTENTION (The PyTorch Way) ===
Multi-Head Attention Output Shape: torch.Size([1, 5, 8])


In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# ==========================================
# 1. DATA PREPARATION (Datasets & DataLoaders)
# ==========================================

# Transforms convert raw images into PyTorch Tensors and normalize pixel values (0 to 1)
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,)) # Mean and Std deviation for MNIST
])

# Download and load the Training Data
print("Loading Training Data...")
train_dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)

# Download and load the Testing (Validation) Data
print("Loading Testing Data...")
test_dataset = datasets.MNIST(root='./data', train=False, download=True, transform=transform)
test_loader = DataLoader(test_dataset, batch_size=1000, shuffle=False)

# ==========================================
# 2. MODEL ARCHITECTURE (The CNN)
# ==========================================

class MNISTClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        # MNIST images are Grayscale (1 channel) and 28x28 pixels
        # Input: [Batch, 1, 28, 28]

        # Convolutional Block
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=3) # Output: 16x26x26
        self.relu = nn.ReLU()
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2) # Output: 16x13x13

        # Flattening
        self.flatten = nn.Flatten()

        # Fully Connected (Linear) Block
        # 16 channels * 13 height * 13 width = 2704
        self.fc1 = nn.Linear(in_features=2704, out_features=128)
        self.fc2 = nn.Linear(in_features=128, out_features=10) # 10 classes for digits 0-9

    def forward(self, x):
        # Feature Extraction
        x = self.conv1(x)
        x = self.relu(x)
        x = self.pool(x)

        # Classification
        x = self.flatten(x)
        x = self.fc1(x)
        x = self.relu(x)
        out = self.fc2(x)
        return out

# Initialize model, loss function, and optimizer
model = MNISTClassifier()
criterion = nn.CrossEntropyLoss() # Used for multi-class classification
optimizer = optim.Adam(model.parameters(), lr=0.001)

# ==========================================
# 3. TRAINING AND VALIDATION LOOP
# ==========================================

epochs = 3

for epoch in range(epochs):
    # --- TRAINING PHASE ---
    model.train() # Set model to training mode
    total_train_loss = 0

    for batch_idx, (images, labels) in enumerate(train_loader):
        # 1. Forward Pass
        predictions = model(images)
        loss = criterion(predictions, labels)

        # 2. Backward Pass & Optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_train_loss += loss.item()

        if batch_idx % 200 == 0:
            print(f"Epoch {epoch+1}/{epochs} | Batch {batch_idx}/{len(train_loader)} | Loss: {loss.item():.4f}")

    avg_train_loss = total_train_loss / len(train_loader)
    print(f"--- Epoch {epoch+1} Complete. Avg Train Loss: {avg_train_loss:.4f} ---")

    # --- VALIDATION PHASE ---
    # We test the model on unseen data to see how accurate it is!
    model.eval() # Set model to evaluation mode (turns off dropout/batchnorm updates)
    correct_predictions = 0
    total_samples = 0

    # torch.no_grad() disables Autograd. We don't need gradients for testing, saving memory!
    with torch.no_grad():
        for images, labels in test_loader:
            predictions = model(images)

            # Get the index of the highest probability (the predicted digit)
            _, predicted_classes = torch.max(predictions, dim=1)

            # Count how many predictions match the true labels
            total_samples += labels.size(0)
            correct_predictions += (predicted_classes == labels).sum().item()

    accuracy = (correct_predictions / total_samples) * 100
    print(f">>> Validation Accuracy: {accuracy:.2f}% <<<\n")

# ==========================================
# 4. SAVING THE MODEL
# ==========================================
# Save the trained weights to a file so we can load it later without retraining
torch.save(model.state_dict(), "mnist_cnn.pth")
print("Model saved successfully as 'mnist_cnn.pth'!")

Loading Training Data...


100%|██████████| 9.91M/9.91M [00:00<00:00, 64.7MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 1.77MB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 15.4MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 7.31MB/s]


Loading Testing Data...
Epoch 1/3 | Batch 0/938 | Loss: 2.3127
Epoch 1/3 | Batch 200/938 | Loss: 0.1333
Epoch 1/3 | Batch 400/938 | Loss: 0.1550
Epoch 1/3 | Batch 600/938 | Loss: 0.1181
Epoch 1/3 | Batch 800/938 | Loss: 0.0742
--- Epoch 1 Complete. Avg Train Loss: 0.1981 ---
>>> Validation Accuracy: 97.24% <<<

Epoch 2/3 | Batch 0/938 | Loss: 0.0818
Epoch 2/3 | Batch 200/938 | Loss: 0.0506
Epoch 2/3 | Batch 400/938 | Loss: 0.0379
Epoch 2/3 | Batch 600/938 | Loss: 0.0508
Epoch 2/3 | Batch 800/938 | Loss: 0.0807
--- Epoch 2 Complete. Avg Train Loss: 0.0683 ---
>>> Validation Accuracy: 98.25% <<<

Epoch 3/3 | Batch 0/938 | Loss: 0.0196
Epoch 3/3 | Batch 200/938 | Loss: 0.0140
Epoch 3/3 | Batch 400/938 | Loss: 0.2786
Epoch 3/3 | Batch 600/938 | Loss: 0.0106
Epoch 3/3 | Batch 800/938 | Loss: 0.0015
--- Epoch 3 Complete. Avg Train Loss: 0.0456 ---
>>> Validation Accuracy: 98.30% <<<

Model saved successfully as 'mnist_cnn.pth'!
