In [ ]:
import torch

In [ ]:
x=torch.tensor([2.0,3.0,4.0])
y=torch.tensor([[2,3],
                [4,5]])

In [ ]:
print(x)
print(y)

tensor([2., 3., 4.])
tensor([[2, 3],
        [4, 5]])


In [ ]:
x.shape


torch.Size([3])

In [ ]:
y.shape

torch.Size([2, 2])

In [ ]:

z=torch.tensor([1,2,3,4,5,6])
z_2d=z.view(2,3)

In [ ]:
print(z_2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
a=torch.tensor([2,3])
b=torch.tensor([5,7])


In [ ]:
print(a+b)

tensor([ 7, 10])


In [ ]:
print(a*b)

tensor([10, 21])


In [ ]:
print(torch.relu(torch.tensor([-1.0,5.0])))

tensor([0., 5.])


In [ ]:
X=torch.tensor([[2,4,5],
               [4,7,8]])
Y=torch.tensor([[3,4],
               [3,9],
               [6,7]])
Z=X@Y
Z_mat=torch.matmul(X,Y)
print("X and Y Matrix Multiplication:",Z)
print("X and Y Matrix Multiplication using the Pytorch:",Z_mat)

X and Y Matrix Multiplication: tensor([[ 48,  79],
        [ 81, 135]])
X and Y Matrix Multiplication using the Pytorch: tensor([[ 48,  79],
        [ 81, 135]])


Autograd, Computational Graphs, and Backpropagation.


In [ ]:
import torch

In [ ]:
w=torch.tensor([3.0],requires_grad=True)
x=torch.tensor([4.0])
y=w*x
y.backward()
print(w.grad)

tensor([4.])


In [ ]:
import torch
import torch.nn as nn


# nn.Module and nn.Linear

In [ ]:
class SimpleNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    self.Layer1=nn.Linear(in_features=2,out_features=1)
  def forward(self,x):
    return self.Layer1(x)
model=SimpleNetwork()
dummy_input=torch.tensor([2.0,3.0])
prediction=model(dummy_input)

print("Model Prediction",prediction)

Model Prediction tensor([-0.2028], grad_fn=<ViewBackward0>)


#  The Full Training Loop Components


In [ ]:
import torch.optim as optim

criterian=nn.MSELoss()
optimizer=optim.SGD(model.parameters(),lr=0.01)

prediction=model(dummy_input)
target=torch.tensor([3.0])

Loss=criterian(prediction,target)
print("Loss:",Loss.item())

optimizer.zero_grad()
Loss.backward()
optimizer.step()

Loss: 10.25802993774414


In [ ]:
import torch
import torch.nn as nn

class MultiLayerPerceptron(nn.Module):
  def __init__(self,input_size,hidden_size,output_size):
    super().__init__()
    self.hidden_layer_layer=nn.Linear(input_size,hidden_size)
    self.output_layer=nn.Linear(hidden_size,output_size)
    self.relu=nn.ReLU()
  def forward(self,x):
    x=self.hidden_layer(x)
    x=self.relu(x)
    out=self.output_layer(x)
    return out
model=MultiLayerPerceptron(input_size=4,hidden_size=10,output_size=1)
print(model)




MultiLayerPerceptron(
  (hidden_layer_layer): Linear(in_features=4, out_features=10, bias=True)
  (output_layer): Linear(in_features=10, out_features=1, bias=True)
  (relu): ReLU()
)
